#!/bin/sh

case "$1" in
  start)
    echo "test" > /tmp/unko
    sleep 10
    wvdial &
    echo "test" > /tmp/unko2
    mpg321 /home/pi/ueki/sounds/initialized_l02c.mp3
    sleep 10
    curl http://www.google.com > /home/pi/test
    mpg321 /home/pi/ueki/sounds/hello_ueki.mp3
    #sleep 5
    #mpg321 /home/pi/ueki/sounds/goodbye.mp3
	;;

  stop)
    echo "FINISH"
	;;

  *)
	exit 1
esac

exit 0
